jobs:
  release:
    name: ${{ inputs.prerelease == 'true' && 'Pre Release' || 'Release' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - continue-on-error: true
      name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        registry-url: https://registry.npmjs.org
    - continue-on-error: true
      name: Checkout Dinky
      uses: actions/checkout@v3
    - continue-on-error: true
      id: build_dinky1_14
      name: Build Dinky ${{ inputs.version }} with Fink 1.14 Pre Release/Release Artifact
      run: "./mvnw -B clean package \\\n        -Dmaven.test.skip=false \\\n     \
        \  -Dspotless.check.skip=true \\\n       -Denforcer.skip=false \\\n      \
        \ -Dmaven.javadoc.skip=true \\\n         -Pprod,scala-2.12,flink-single-version,flink-1.14,maven-central,web,fast\
        \ \\\n       --no-snapshot-updates\n"
    - continue-on-error: true
      id: build_dinky1_15
      name: Build Dinky ${{ inputs.version }} with Fink 1.15 Pre Release/Release Artifact
      run: "./mvnw -B clean package \\\n        -Dmaven.test.skip=false \\\n     \
        \  -Dspotless.check.skip=true \\\n       -Denforcer.skip=false \\\n      \
        \ -Dmaven.javadoc.skip=true \\\n         -Pprod,scala-2.12,flink-single-version,flink-1.15,maven-central,web,fast\
        \ \\\n       --no-snapshot-updates\n"
    - continue-on-error: true
      id: build_dinky1_16
      name: Build Dinky ${{ inputs.version }} with Fink 1.16 Pre Release/Release Artifact
      run: "./mvnw -B clean package \\\n        -Dmaven.test.skip=false \\\n     \
        \  -Dspotless.check.skip=true \\\n       -Denforcer.skip=false \\\n      \
        \ -Dmaven.javadoc.skip=true \\\n         -Pprod,scala-2.12,flink-single-version,flink-1.16,maven-central,web,fast\
        \ \\\n       --no-snapshot-updates\n"
    - continue-on-error: true
      id: build_dinky1_17
      name: Build Dinky ${{ inputs.version }} with Fink 1.17 Pre Release/Release Artifact
      run: "./mvnw -B clean package \\\n        -Dmaven.test.skip=false \\\n     \
        \  -Dspotless.check.skip=true \\\n       -Denforcer.skip=false \\\n      \
        \ -Dmaven.javadoc.skip=true \\\n         -Pprod,scala-2.12,flink-single-version,flink-1.17,maven-central,web,fast\
        \ \\\n       --no-snapshot-updates\n"
    - continue-on-error: true
      id: build_dinky1_18
      name: Build Dinky ${{ inputs.version }} with Fink 1.18 Pre Release/Release Artifact
      run: "./mvnw -B clean package \\\n        -Dmaven.test.skip=false \\\n     \
        \  -Dspotless.check.skip=true \\\n       -Denforcer.skip=false \\\n      \
        \ -Dmaven.javadoc.skip=true \\\n         -Pprod,scala-2.12,flink-single-version,flink-1.18,maven-central,web,fast\
        \ \\\n       --no-snapshot-updates\n"
    - continue-on-error: true
      name: Automatic Upload Releases to GitHub Releases Page
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: latest
        body: '${{ inputs.release_notes }}

          '
        draft: false
        files: ./build/dinky-release-*.tar.gz
        prerelease: false
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        title: Dinky ${{ inputs.version }} Release
        upload_url: https://github.com/DataLinkDC/dinky/releases
name: Release Dinky
on:
  repository_dispatch:
    types: trigger-ga___auto-realease-ci.yml
