jobs:
  code-review:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LANGUAGE: Chinese
        MAX_PATCH_LENGTH: 10000
        MODEL: gpt-3.5-turbo
        OPENAI_API_ENDPOINT: https://api.openai.com/v1
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PROMPT: Please check if there are any confusions or irregularities in the
          following code diffs. If there are, please point them out. If not, please
          reply with "No problem".
        max_tokens: 10000
        temperature: 1
        top_p: 1
      name: Code Review
      uses: anc95/ChatGPT-CodeReview@main
name: Code Review Robot
on:
  repository_dispatch:
    types: trigger-ga___code-review.yml
permissions:
  contents: read
  pull-requests: write
