jobs:
  build_releases:
    name: build releases
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
        path: '~/.m2/repository/*/*/*

          '
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Build and Package
      run: "./mvnw -B clean install \\\n       -Dmaven.test.skip=true \\\n       -Dspotless.check.skip=true\
        \ \\\n       -P prod,scala-2.12,flink-all,web,maven-central,fast \\\n    \
        \   --no-snapshot-updates\n"
    - continue-on-error: true
      name: Upload release file
      uses: actions/upload-artifact@v3
      with:
        name: release-file
        path: ./build/dinky-release-*.tar.gz
  dinky_flink_image:
    name: docker dinky flink image
    needs:
    - dinky_image
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Move Dockerfile
      run: 'cp -r ./docker/Dockerfile* ./

        '
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: set the flink_big_version
      run: 'echo FLINK_BIG_VERSION=${FLINK_VERSION%.*} >> $GITHUB_ENV

        '
    - continue-on-error: true
      name: Download math result for job 1
      uses: actions/download-artifact@v3
      with:
        name: release-file
        path: ./build/
    - continue-on-error: true
      if: ${{ matrix.url == 'registry.cn-hangzhou.aliyuncs.com'}}
      name: Log in to the Container registry,url -> ${{ matrix.url }}
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKER_ALIYUN_PASS }}
        registry: ${{ matrix.url }}
        username: ${{ secrets.DOCKER_ALIYUN_USER }}
    - continue-on-error: true
      if: ${{ matrix.url == 'docker.io'}}
      name: Log in to the Container registry,url -> ${{ matrix.url }}
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKER_IO_PASS }}
        registry: ${{ matrix.url }}
        username: ${{ secrets.DOCKER_IO_USER }}
    - continue-on-error: true
      name: push docker dinky image
      uses: docker/build-push-action@v2
      with:
        build-args: 'FLINK_VERSION=${{ matrix.FLINK_VERSION }}

          DINKY_IMAGE=${{ matrix.url }}/${{ matrix.namespace }}/dinky-standalone-server:${{
          inputs.version }}

          FLINK_BIG_VERSION=${{ matrix.FLINK_BIG_VERSION }}

          '
        context: .
        file: DockerfileDinkyFlink
        push: false
        tags: ${{ matrix.url }}/${{ matrix.namespace }}/dinky-standalone-server:${{
          inputs.version }}-flink-${{matrix.FLINK_BIG_VERSION }}
    strategy:
      fail-fast: true
      matrix:
        FLINK_VERSION:
        - 1.14.6
        - 1.15.4
        - 1.16.3
        - 1.17.2
        - 1.18.1
        - 1.19.0
        include:
        - namespace: dinky
          url: registry.cn-hangzhou.aliyuncs.com
        - namespace: dinkydocker
          url: docker.io
        - FLINK_BIG_VERSION: 1.14
          FLINK_VERSION: 1.14.6
        - FLINK_BIG_VERSION: 1.15
          FLINK_VERSION: 1.15.4
        - FLINK_BIG_VERSION: 1.16
          FLINK_VERSION: 1.16.3
        - FLINK_BIG_VERSION: 1.17
          FLINK_VERSION: 1.17.2
        - FLINK_BIG_VERSION: 1.18
          FLINK_VERSION: 1.18.1
        - FLINK_BIG_VERSION: 1.19
          FLINK_VERSION: 1.19.0
        url:
        - registry.cn-hangzhou.aliyuncs.com
        - docker.io
  dinky_image:
    name: docker dinky image
    needs:
    - build_releases
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Move Dockerfile
      run: 'cp -r ./docker/Dockerfile* ./

        '
    - continue-on-error: true
      name: Download math result for job 1
      uses: actions/download-artifact@v3
      with:
        name: release-file
        path: ./build/
    - continue-on-error: true
      if: ${{ matrix.url == 'registry.cn-hangzhou.aliyuncs.com'}}
      name: Log in to the Container registry,url -> ${{ matrix.url }}
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKER_ALIYUN_PASS }}
        registry: ${{ matrix.url }}
        username: ${{ secrets.DOCKER_ALIYUN_USER }}
    - continue-on-error: true
      if: ${{ matrix.url == 'docker.io'}}
      name: Log in to the Container registry,url -> ${{ matrix.url }}
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKER_IO_PASS }}
        registry: ${{ matrix.url }}
        username: ${{ secrets.DOCKER_IO_USER }}
    - continue-on-error: true
      name: push docker dinky image
      uses: docker/build-push-action@v2
      with:
        build-args: 'DINKY_VERSION=${{ inputs.version }}

          '
        context: .
        file: Dockerfile
        push: false
        tags: ${{ matrix.url }}/${{ matrix.namespace }}/dinky-standalone-server:${{
          inputs.version }}
    strategy:
      fail-fast: true
      matrix:
        include:
        - namespace: dinky
          url: registry.cn-hangzhou.aliyuncs.com
        - namespace: dinkydocker
          url: docker.io
        url:
        - registry.cn-hangzhou.aliyuncs.com
        - docker.io
  dinky_mysql_image:
    name: dinky mysql image
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      if: ${{ matrix.url == 'registry.cn-hangzhou.aliyuncs.com'}}
      name: Log in to the Container registry,url -> ${{ matrix.url }}
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKER_ALIYUN_PASS }}
        registry: ${{ matrix.url }}
        username: ${{ secrets.DOCKER_ALIYUN_USER }}
    - continue-on-error: true
      if: ${{ matrix.url == 'docker.io'}}
      name: Log in to the Container registry,url -> ${{ matrix.url }}
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKER_IO_PASS }}
        registry: ${{ matrix.url }}
        username: ${{ secrets.DOCKER_IO_USER }}
    - continue-on-error: true
      name: push docker dinky mysql image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/DockerfileMysql
        push: false
        tags: ${{ matrix.url }}/${{ matrix.namespace }}/dinky-mysql-server:${{ inputs.version
          }}
    strategy:
      fail-fast: true
      matrix:
        include:
        - namespace: dinky
          url: registry.cn-hangzhou.aliyuncs.com
        - namespace: dinkydocker
          url: docker.io
        url:
        - registry.cn-hangzhou.aliyuncs.com
        - docker.io
name: Docker Build
on:
  repository_dispatch:
    types: trigger-ga___docker_build.yaml
