jobs:
  build-documentation:
    if: github.repository == 'DataLinkDC/dinky'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Build documentation
      run: 'cd docs && npm install --prefer-offline --no-audit --progress=false --legacy-peer-deps
        \

        &&  npm run build

        '
    - continue-on-error: true
      name: Upload documentation
      uses: burnett01/rsync-deployments@5.2
      with:
        path: docs/build/
        remote_host: ${{ secrets.RSYNC_HOST }}
        remote_key: ${{ secrets.RSYNC_KEY }}
        remote_path: ${{ secrets.RSYNC_PATH }}
        remote_port: ${{ secrets.RSYNC_PORT }}
        remote_user: ${{ secrets.RSYNC_USER }}
        switches: --archive --compress --delete-before
name: Build documentation
on:
  repository_dispatch:
    types: trigger-ga___docs.yml
