concurrency:
  group: backend-${{ github.event.pull_request.number || github.ref }}
jobs:
  format:
    if: github.repository != 'DataLinkDC/dinky' && vars.FORMAT == 'true'
    name: Format Code
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}
        token: ${{ secrets.TOKEN }}
    - continue-on-error: true
      id: filter
      uses: dorny/paths-filter@v2
      with:
        filters: "frontend:\n  - 'dinky-web/**'\nbackend:\n  - '!dinky-web/**'   \
          \        \n"
    - continue-on-error: true
      if: steps.filter.outputs.backend == 'true'
      name: Run spotless apply
      run: ./mvnw -T 4C -B --no-snapshot-updates clean spotless:apply -P flink-all
    - continue-on-error: true
      if: steps.filter.outputs.frontend == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - continue-on-error: true
      id: npm-cache-dir
      if: steps.filter.outputs.frontend == 'true'
      name: Get npm cache directory
      run: 'echo "::set-output name=dir::$(npm config get cache)"

        '
    - continue-on-error: true
      id: npm-cache
      if: steps.filter.outputs.frontend == 'true'
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('dinky-web/**/package.json') }}
        path: '${{ steps.npm-cache-dir.outputs.dir }}

          dinky-web/dist

          '
        restore-keys: '${{ runner.os }}-node-

          '
    - continue-on-error: true
      if: steps.filter.outputs.frontend == 'true'
      name: Install Dependencies
      run: cd dinky-web && npm install --only=dev --prefer-offline --no-audit --progress=false
        --legacy-peer-deps
    - continue-on-error: true
      if: steps.filter.outputs.frontend == 'true'
      name: Run frontend format
      run: cd dinky-web && npm run lint:prettier
    - continue-on-error: true
      id: git-check
      name: Check for modified files
      run: 'echo "modified=$(if git diff-index --quiet HEAD --; then echo "false";
        else echo "true"; fi)" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      if: steps.git-check.outputs.modified == 'true'
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Spotless Apply
name: Format Code in fork repo
on:
  repository_dispatch:
    types: trigger-ga___format_code.yaml
