jobs:
  issue-close-require:
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: github.event.issue.number != 66 ||  github.event.issue.number != 884
      name: need reproduce
      uses: actions-cool/issues-helper@v3
      with:
        actions: close-issues
        body: "Hi @${{ github.event.issue.user.login }}, Because this issue was marked\
          \ as requiring detailed reproduction steps, no response was received for\
          \ 10 days. The issue is now closed. If you have any questions, please comment\
          \ and reply.\n\nHi @${{ github.event.issue.user.login }}, \u7531\u4E8E\u8BE5\
          \ issue \u88AB\u6807\u8BB0\u4E3A\u9700\u8981\u63D0\u4F9B\u8BE6\u7EC6\u590D\
          \u73B0\u6B65\u9AA4\uFF0C\u5374 10 \u5929\u672A\u6536\u5230\u56DE\u5E94\u3002\
          \u73B0\u5173\u95ED issue\uFF0C\u82E5\u6709\u4EFB\u4F55\u95EE\u9898\uFF0C\
          \u53EF\u8BC4\u8BBA\u56DE\u590D\u3002\n"
        inactive-day: 10
        labels: Need Reproduce
    - continue-on-error: true
      if: github.event.issue.number != 66 ||  github.event.issue.number != 884
      name: duplicate issue
      uses: actions-cool/issues-helper@v3
      with:
        actions: close-issues
        body: "Hi @${{ github.event.issue.user.login }}, Since this issue was marked\
          \ as a duplicate issue, no response was received for 3 days. The issue is\
          \ now closed. If you have any questions, please comment and reply\n\nHi\
          \ @${{ github.event.issue.user.login }}, \u7531\u4E8E\u8BE5 issue \u88AB\
          \u6807\u8BB0\u4E3A\u91CD\u590D\u95EE\u9898\uFF0C\u5374 3 \u5929\u672A\u6536\
          \u5230\u56DE\u5E94\u3002\u73B0\u5173\u95ED issue\uFF0C\u82E5\u6709\u4EFB\
          \u4F55\u95EE\u9898\uFF0C\u53EF\u8BC4\u8BBA\u56DE\u590D\u3002\n"
        inactive-day: 3
        labels: Duplicate
    - continue-on-error: true
      if: github.event.issue.number != 66 ||  github.event.issue.number != 884
      name: Fixed issue
      uses: actions-cool/issues-helper@v3
      with:
        actions: close-issues
        body: "Hi @${{ github.event.issue.user.login }}, Since this issue was marked\
          \ as fixed, no response has been received for 2 days. The issue is now closed.\
          \ If you have any questions, please comment and reply.\n\nHi @${{ github.event.issue.user.login\
          \ }}, \u7531\u4E8E\u8BE5 issue \u88AB\u6807\u8BB0\u4E3A\u5DF2\u4FEE\u590D\
          \uFF0C\u5374 2 \u5929\u672A\u6536\u5230\u56DE\u5E94\u3002\u73B0\u5173\u95ED\
          \ issue\uFF0C\u82E5\u6709\u4EFB\u4F55\u95EE\u9898\uFF0C\u53EF\u8BC4\u8BBA\
          \u56DE\u590D\u3002\n"
        inactive-day: 2
        labels: Fixed
    - continue-on-error: true
      if: github.event.issue.number != 66 ||  github.event.issue.number != 884
      name: More Information Required
      uses: actions-cool/issues-helper@v3
      with:
        actions: close-issues
        body: "Hi @${{ github.event.issue.user.login }}, Since this issue was marked\
          \ as requiring more information, no response was received for 7 days. The\
          \ issue is now closed. If you have any questions, please comment and reply.\n\
          \nHi @${{ github.event.issue.user.login }}, \u7531\u4E8E\u8BE5 issue \u88AB\
          \u6807\u8BB0\u4E3A\u9700\u8981\u66F4\u591A\u4FE1\u606F\uFF0C\u5374 7 \u5929\
          \u672A\u6536\u5230\u56DE\u5E94\u3002\u73B0\u5173\u95ED issue\uFF0C\u82E5\
          \u6709\u4EFB\u4F55\u95EE\u9898\uFF0C\u53EF\u8BC4\u8BBA\u56DE\u590D\u3002\
          \n"
        inactive-day: 7
        labels: More Information Required
name: Issue Close Require
on:
  repository_dispatch:
    types: trigger-ga___issue-close-require.yml
permissions:
  contents: read
