jobs:
  check-inactive:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: check-inactive
      uses: actions-cool/issues-helper@v1.7
      with:
        actions: check-inactive
        body: "Hello @${{ github.event.issue.user.login }}, this issue has not been\
          \ active for more than 30 days. This issue will be closed in 7 days if there\
          \ is no response. If you have any questions, you can comment and reply.\n\
          \n\u4F60\u597D @${{ github.event.issue.user.login }}, \u8FD9\u4E2A issue\
          \ 30 \u5929\u5185\u6CA1\u6709\u6D3B\u8DC3\uFF0C7 \u5929\u540E\u5C06\u5173\
          \u95ED\uFF0C\u5982\u9700\u56DE\u590D\uFF0C\u53EF\u4EE5\u8BC4\u8BBA\u56DE\
          \u590D\u3002\n"
        inactive-day: 30
        inactive-label: Invalid
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: ${{ success() }}
      name: Add inactive labels
      uses: actions-cool/issues-helper@v3
      with:
        actions: add-labels
        issue-number: ${{ github.event.issue.number }}
        labels: Invalid
        token: ${{ secrets.GITHUB_TOKEN }}
name: Issue Check Inactive
on:
  repository_dispatch:
    types: trigger-ga___issue-check-inactive.yml
