jobs:
  issueRobot:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout ${{ github.ref }}
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        submodules: true
    - continue-on-error: true
      name: Translation into English in issue
      uses: ./.github/actions/translate-on-issue
      with:
        translate-body: false
        translate-title: true
name: Translation Issue Robot
on:
  repository_dispatch:
    types: trigger-ga___issue-rebot.yml
