jobs:
  reply-help:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: github.event.label.name == 'Need Reproduce'
      name: Need Provide Reproduce Steps
      uses: actions-cool/issues-helper@v1.7
      with:
        actions: create-comment
        body: "Hello @${{ github.event.issue.user.login }}, we need you to provide\
          \ reproduction steps so that we can help you troubleshoot the problem. Issues\
          \ are marked \\`Need Reproduce\\`.\n\n\u4F60\u597D @${{ github.event.issue.user.login\
          \ }}, \u6211\u4EEC\u9700\u8981\u4F60\u63D0\u4F9B\u590D\u73B0\u6B65\u9AA4\
          \u4EE5\u4FBF\u4E8E\u6211\u4EEC\u5E2E\u4F60\u6392\u67E5\u95EE\u9898\uFF0C\
          Issues \u6807\u6CE8\u4E3A \\`Need Reproduce\\` \u3002\n"
        issue-number: ${{ github.event.issue.number }}
    - continue-on-error: true
      if: github.event.label.name == 'Duplicate'
      name: Action Duplicate Issue
      uses: actions-cool/issues-helper@v1.7
      with:
        actions: create-comment
        body: "Hello @${{ github.event.issue.user.login }}, thank you for your feedback,\
          \ but this issue has been reported before. You can search for keywords in\
          \ the Issue list to view it. Issues are marked as \\`Duplicate\\`.\n\n\u4F60\
          \u597D @${{ github.event.issue.user.login }}, \u611F\u8C22\u4F60\u7684\u53CD\
          \u9988, \u4F46\u662F\u6B64\u95EE\u9898\u5DF2\u7ECF\u88AB\u53CD\u9988\u8FC7\
          \u4E86\uFF0C\u4F60\u53EF\u4EE5\u5728 Issue \u5217\u8868\u4E2D\u641C\u7D22\
          \u5173\u952E\u5B57\u6765\u67E5\u770B, Issues \u6807\u6CE8\u4E3A \\`Duplicate\\\
          ` \u3002\n"
        issue-number: ${{ github.event.issue.number }}
    - continue-on-error: true
      if: github.event.label.name == 'Fixed'
      name: Action Fixed Issue
      uses: actions-cool/issues-helper@v1.7
      with:
        actions: create-comment
        body: "Hello @${{ github.event.issue.user.login }}, thank you for your feedback,\
          \ but this issue has been fixed. You can search for keywords in the Issue\
          \ list to view it. Issues are marked as \\`Fixed\\`.\n\n\u4F60\u597D @${{\
          \ github.event.issue.user.login }}, \u611F\u8C22\u4F60\u7684\u53CD\u9988\
          , \u4F46\u662F\u6B64\u95EE\u9898\u5DF2\u7ECF\u88AB\u4FEE\u590D\u4E86\uFF0C\
          \u4F60\u53EF\u4EE5\u5728 Issue \u5217\u8868\u4E2D\u641C\u7D22\u5173\u952E\
          \u5B57\u6765\u67E5\u770B, Issues \u6807\u6CE8\u4E3A \\`Fixed\\` \u3002\n"
        issue-number: ${{ github.event.issue.number }}
    - continue-on-error: true
      if: github.event.label.name == 'Supported'
      name: Action Supported Issue
      uses: actions-cool/issues-helper@v1.7
      with:
        actions: create-comment
        body: "Hello @${{ github.event.issue.user.login }}, thank you for your suggestion,\
          \ but this function has been implemented. You can search for keywords in\
          \ the Issue list to view it. Issues are marked \\`Supported\\`\n\n\u4F60\
          \u597D @${{ github.event.issue.user.login }}, \u611F\u8C22\u4F60\u7684\u5EFA\
          \u8BAE, \u4F46\u662F\u6B64\u529F\u80FD\u5DF2\u7ECF\u5B9E\u73B0\u4E86\uFF0C\
          \u4F60\u53EF\u4EE5\u5728 Issue \u5217\u8868\u4E2D\u641C\u7D22\u5173\u952E\
          \u5B57\u6765\u67E5\u770B, Issues \u6807\u6CE8\u4E3A \\`Supported\\` \u3002\
          \n"
        issue-number: ${{ github.event.issue.number }}
    - continue-on-error: true
      if: github.event.label.name == 'Wont Fix'
      name: Action Wont Fix Issue
      uses: actions-cool/issues-helper@v1.7
      with:
        actions: create-comment
        body: "Hello @${{ github.event.issue.user.login }}, thank you for your feedback,\
          \ but this issue will not be fixed. You can search for keywords in the Issue\
          \ list to view it. Issues are marked \\`Wont Fix\\`\n\n\u4F60\u597D @${{\
          \ github.event.issue.user.login }}, \u611F\u8C22\u4F60\u7684\u53CD\u9988\
          , \u4F46\u662F\u6B64\u95EE\u9898\u4E0D\u4F1A\u88AB\u4FEE\u590D\uFF0C\u4F60\
          \u53EF\u4EE5\u5728 Issue \u5217\u8868\u4E2D\u641C\u7D22\u5173\u952E\u5B57\
          \u6765\u67E5\u770B, Issues \u6807\u6CE8\u4E3A \\`Wont Fix\\` \u3002"
        issue-number: ${{ github.event.issue.number }}
name: Issue Reply Check
on:
  repository_dispatch:
    types: trigger-ga___issue-reply.yml
