jobs:
  add-reviewer:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Add assignees
      uses: actions-cool/issues-helper@main
      with:
        actions: add-assignees
        assignees: ${{ github.event.pull_request.user.login }}
        issue-number: ${{ github.event.pull_request.number }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Add reviewers
      uses: actions-cool/pr-welcome@main
      with:
        pr-emoji: +1, rocket
        review-creator: false
        reviewers: zackyoungh,gaoyan1998,Zzm0809,aiwenmo
        token: ${{ secrets.GITHUB_TOKEN }}
name: PR Auto Assign Reviewer
on:
  repository_dispatch:
    types: trigger-ga___pr-reviewer-assign.yml
